### ISSUE TITLE
2018-11-16 の記事にリンクのミス？

### ISSUE THREAD

**Issue by Wintus** [Nymphium/nymphium.github.io#2]
## 問題
https://nymphium.github.io/2018/11/16/Lua-VM%E3%81%AB%E8%A6%8B%E3%82%8B%E5%A4%9A%E5%80%A4%E3%81%AE%E6%89%B1%E3%81%84.html#3-1-lua-vm
リンクから飛べなかった

## コード
おそらくここ
https://github.com/Nymphium/nymphium.github.io/blob/a422d4ae8b52fd07f4ba6c8da77b968f51dd092b/_posts/2018-11-16-Lua%20VM%E3%81%AB%E8%A6%8B%E3%82%8B%E5%A4%9A%E5%80%A4%E3%81%AE%E6%89%B1%E3%81%84.md#L356

https://nymphium.github.io/2016/04/25/luaquiz.html

**Comment by Nymphium** [comment]
修正しました､ありがとうございました :pray:
